import Login from './Login'
import SingIn from './SingIn'
import BoxProduitTableView  from './BoxProduitTableView'
import BoxProduitCardView from './BoxProduitCardView'
import Container from './Container'
import Menus from './Menus'
import Messages from './Messages'
import Error from './Error'
import Commande from './Commande'
import NouveauProduit from './NouveauProduit'
import Parametre from './Parametre'
import MeilleurProduit from './MeilleurProduit'
import BoxFilter from './BoxFilter'

export {Login, SingIn, NouveauProduit, BoxProduitTableView, BoxProduitCardView, Container, Menus, Messages, Commande, Parametre,BoxFilter, MeilleurProduit, Error}
